### ISSUE TITLE
Tracking Ideas

### ISSUE THREAD

**Issue by SebastianAment** [MingChiangChang/CrystalTree.jl#3]
Opening an issue to keep track of the best first search ideas:

- [ ] Best first search 
    - [x] using a single inner product with the current residual
    - [ ] using multiplicatively shifted versions of phases
    - [ ] using Monte Carlo sampled versions of phases

**Comment by MingChiangChang** [comment]
- [ ] Lazy tree creation: Create tree when it has to be expanded. Could be easier to code.

**Comment by MingChiangChang** [comment]
Use marginal likelihood to guide tree search.
- [ ] Method
- [ ] Implementation
